/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 fashionGenesis.gltf --transform
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/fashionGenesis-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, -80, -1.5]} >
      <primitive object={nodes.Joint} />
      <primitive object={nodes.body} />
      <primitive object={nodes.eye_L} />
      <primitive object={nodes.eye_R} />
      <primitive object={nodes.eyelash_L} />
      <primitive object={nodes.eyelash_R} />
      <primitive object={nodes.tooth} />
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['PD-00247052_medium_FRONT_2738']} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials['PD-00247052_medium_FRONT_2738']} />
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials['PD-00247052_medium_FRONT_2738']} />
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials['PD-00247052_medium_FRONT_2738']} />
      <mesh geometry={nodes.Cloth_mesh_16.geometry} material={materials.Necklace_FRONT_2709} />
      <mesh geometry={nodes.Cloth_mesh_17.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_18.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_19.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_20.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_21.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_22.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_23.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_24.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_25.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_26.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_27.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_28.geometry} material={materials.Gloves_FRONT_2716} />
      <mesh geometry={nodes.Cloth_mesh_29.geometry} material={materials['PD-00247052_medium_FRONT_2738']} />
      <mesh geometry={nodes.Cloth_mesh_30.geometry} material={materials['PD-00247052_medium_FRONT_2738']} />
      <mesh geometry={nodes.Cloth_mesh_31.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_32.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_33.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_34.geometry} material={materials.Dress_FRONT_2687} />
      <mesh geometry={nodes.Cloth_mesh_35.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_36.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_37.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_38.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_39.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_40.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_41.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_42.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_43.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_44.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_45.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_46.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_47.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_48.geometry} material={materials['FABRIC 2_FRONT_2721']} />
      <mesh geometry={nodes.Cloth_mesh_49.geometry} material={materials.Brim_FRONT_2726} />
      <mesh geometry={nodes.Cloth_mesh_50.geometry} material={materials.Brim_FRONT_2726} />
      <mesh geometry={nodes.Cloth_mesh_51.geometry} material={materials.Brim_FRONT_2726} />
      <mesh geometry={nodes.Cloth_mesh_52.geometry} material={materials['FABRIC 1_FRONT_2733']} />
      <mesh geometry={nodes.Cloth_mesh_53.geometry} material={materials.Brim_FRONT_2726} />
      <mesh geometry={nodes.Cloth_mesh_54.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.Cloth_mesh_55.geometry} material={materials['PD-00247052_medium_FRONT_2692']} />
      <mesh geometry={nodes.BindedTrim_36520_mesh.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_36520_mesh_1.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_36715_mesh.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_36715_mesh_1.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_36910_mesh.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_36910_mesh_1.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_37105_mesh.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_37105_mesh_1.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_37402_mesh.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_37402_mesh_1.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_37723_mesh.geometry} material={materials.Material2937} />
      <mesh geometry={nodes.BindedTrim_37723_mesh_1.geometry} material={materials.Material2937} />
    </group>
  )
}

useGLTF.preload('/fashionGenesis-transformed.glb')
